name                  = "takanolabs"
compatibility_date    = "2024-09-23"
pages_build_output_dir = "."

[[d1_databases]]
binding       = "DB"
database_name = "CalidadAlimentaria"
database_id   = "09086825-a9bc-49f3-b57f-39bc0df7b5b0"
